// Code generated by wireinjectgen; DO NOT EDIT.
package wire

import (
	"github.com/google/wire"
	services "github.com/muhriddinnorqulov/skeleton/src/core/application/services"
	tasks "github.com/muhriddinnorqulov/skeleton/src/core/application/tasks"
	entityusecases "github.com/muhriddinnorqulov/skeleton/src/core/application/usecases/entityusecases"
	asynctask "github.com/muhriddinnorqulov/skeleton/src/entrypoint/asynctask"
	handlers "github.com/muhriddinnorqulov/skeleton/src/entrypoint/asynctask/handlers"
	http "github.com/muhriddinnorqulov/skeleton/src/entrypoint/http"
	groups "github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/groups"
	entity "github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/handlers/entity"
	health "github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/handlers/health"
	ws "github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/handlers/ws"
	middlewares "github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/interceptor/middlewares"
	asyncq "github.com/muhriddinnorqulov/skeleton/src/infrastructure/asyncq"
	middlewares2 "github.com/muhriddinnorqulov/skeleton/src/infrastructure/asyncq/middlewares"
	db "github.com/muhriddinnorqulov/skeleton/src/infrastructure/db"
	echohttp "github.com/muhriddinnorqulov/skeleton/src/infrastructure/echohttp"
	defaults "github.com/muhriddinnorqulov/skeleton/src/infrastructure/echohttp/defaults"
	handlers2 "github.com/muhriddinnorqulov/skeleton/src/infrastructure/echohttp/defaults/handlers"
	env "github.com/muhriddinnorqulov/skeleton/src/infrastructure/env"
	file "github.com/muhriddinnorqulov/skeleton/src/infrastructure/file"
	gateway "github.com/muhriddinnorqulov/skeleton/src/infrastructure/gateway"
	network "github.com/muhriddinnorqulov/skeleton/src/infrastructure/gateway/network"
	gorillaws "github.com/muhriddinnorqulov/skeleton/src/infrastructure/gorillaws"
	middlewares3 "github.com/muhriddinnorqulov/skeleton/src/infrastructure/gorillaws/middlewares"
	logger "github.com/muhriddinnorqulov/skeleton/src/infrastructure/logger"
	payment "github.com/muhriddinnorqulov/skeleton/src/infrastructure/payment"
	repository "github.com/muhriddinnorqulov/skeleton/src/infrastructure/persistence/repository"
	security "github.com/muhriddinnorqulov/skeleton/src/infrastructure/security"
	storage "github.com/muhriddinnorqulov/skeleton/src/infrastructure/storage"
)

var ProviderSet = wire.NewSet(
	services.NewEntityService,
	tasks.NewProcessEntityTask,
	entityusecases.NewCreateEntityUseCase,
	entityusecases.NewGetEntityUseCase,
	asynctask.NewAsyncApp,
	handlers.NewProcessEntityHandler,
	http.NewApp,
	groups.NewEntityGroup,
	groups.NewHealthGroup,
	groups.NewWsGroup,
	entity.NewCreateEntityHandler,
	health.NewHealthHandler,
	ws.NewExampleWsHandler,
	middlewares.NewJwtAuthMiddleware,
	middlewares.NewResponseMiddleware,
	asyncq.NewAsyncContextImpl,
	asyncq.NewAsynqClient,
	asyncq.NewAsynqConfig,
	asyncq.NewAsynqRedisClientOpt0,
	asyncq.NewAsynqServeMux,
	asyncq.NewAsynqServer,
	asyncq.NewAsynqServerImpl,
	asyncq.NewAsynqTaskPublisher,
	middlewares2.NewTaskLogMiddleware,
	db.NewAtomicTxImpl,
	db.NewDatabase,
	db.NewGormDB,
	echohttp.NewEcho,
	echohttp.NewEchoServerImpl,
	defaults.NewConsoleLoggerMiddleware,
	defaults.NewDeveloperBasicAuthMiddleware,
	defaults.NewDevelopmentGroup,
	defaults.NewHttpLoggerMiddleware,
	defaults.NewRecoveryMiddleware,
	defaults.NewRequestValidator,
	handlers2.NewAsynqmonHandler,
	env.NewConfigAdapter,
	env.NewEnv,
	file.NewHtmlRendererImpl,
	gateway.NewExternalGatewayImpl,
	network.NewCHTTpClient,
	network.NewHTTPClient,
	gorillaws.NewConnectionStore,
	gorillaws.NewConsumer,
	gorillaws.NewDialer,
	gorillaws.NewGorillaUpgrader,
	gorillaws.NewMux,
	gorillaws.NewWsImpl,
	middlewares3.NewLoggingMiddleware,
	middlewares3.NewRecovererMiddleware,
	logger.NewAsyncLogger,
	logger.NewConsoleLogger,
	logger.NewGatewayLogger,
	logger.NewHttpLogger,
	logger.NewWsLogger,
	payment.NewPaymentAdapter,
	repository.NewBaseRepository,
	repository.NewEntityRepositoryImpl,
	security.NewBcryptAdapter,
	security.NewJwtTokenAdapter,
	storage.NewLocalFileStorage,
)
