services:

  skeleton-postgres:
    image: postgres:17
    container_name: PROJECT_NAME-postgres
    ports:
      - "5432:5432"
    env_file:
      - ./../.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.volumes/pg_data:/var/lib/postgresql/data
    networks:
      - skeleton-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  skeleton-redis:
    image: redis:7.4
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: skeleton-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.volumes/redis:/data
    networks:
      - skeleton-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  skeleton-network:
    driver: bridge
