// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/muhriddinnorqulov/skeleton/src/core/application/usecases/entityusecases"
	"github.com/muhriddinnorqulov/skeleton/src/entrypoint/asynctask"
	handlers2 "github.com/muhriddinnorqulov/skeleton/src/entrypoint/asynctask/handlers"
	"github.com/muhriddinnorqulov/skeleton/src/entrypoint/http"
	"github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/groups"
	"github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/handlers/entity"
	"github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/handlers/ws"
	"github.com/muhriddinnorqulov/skeleton/src/entrypoint/http/interceptor/middlewares"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/asyncq"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/db"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/echohttp"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/echohttp/defaults"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/echohttp/defaults/handlers"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/env"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/gorillaws"
	middlewares2 "github.com/muhriddinnorqulov/skeleton/src/infrastructure/gorillaws/middlewares"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/logger"
	"github.com/muhriddinnorqulov/skeleton/src/infrastructure/persistence/repository"
)

// Injectors from wire.go:

func InitHttpApp() *http.App {
	requestValidator := defaults.NewRequestValidator()
	echo := echohttp.NewEcho(requestValidator)
	envEnv := env.NewEnv()
	redisClientOpt := async.NewAsynqRedisClientOpt0(envEnv)
	httpHandler := handlers.NewAsynqmonHandler(redisClientOpt)
	developmentGroup := defaults.NewDevelopmentGroup(httpHandler)
	developerBasicAuthMiddleware := defaults.NewDeveloperBasicAuthMiddleware(envEnv)
	httpLogger := logger.NewHttpLogger()
	recoveryMiddleware := defaults.NewRecoveryMiddleware(httpLogger)
	httpLoggerMiddleware := defaults.NewHttpLoggerMiddleware(httpLogger)
	consoleLogger := logger.NewConsoleLogger()
	consoleLoggerMiddleware := defaults.NewConsoleLoggerMiddleware(consoleLogger)
	httpServer := echohttp.NewEchoServerImpl(echo, envEnv, developmentGroup, developerBasicAuthMiddleware, recoveryMiddleware, httpLoggerMiddleware, consoleLoggerMiddleware)
	jwtAuthMiddleware := middlewares.NewJwtAuthMiddleware()
	responseMiddleware := middlewares.NewResponseMiddleware()
	gormDB := db.NewGormDB(envEnv)
	database := db.NewDatabase(gormDB)
	atomic := db.NewAtomicTxImpl(database)
	baseRepository := repository.NewBaseRepository(database)
	entityRepository := repository.NewEntityRepositoryImpl(baseRepository)
	createEntityUseCase := entityusecases.NewCreateEntityUseCase(atomic, entityRepository)
	createEntityHandler := entity.NewCreateEntityHandler(createEntityUseCase)
	entityGroup := groups.NewEntityGroup(createEntityHandler)
	gorillaUpgrader := gorillaws.NewGorillaUpgrader()
	configProvider := env.NewConfigAdapter(envEnv)
	dialer := gorillaws.NewDialer(configProvider)
	connectionStore := gorillaws.NewConnectionStore()
	mux := gorillaws.NewMux()
	consumer := gorillaws.NewConsumer(mux)
	wsLogger := logger.NewWsLogger()
	loggingMiddleware := middlewares2.NewLoggingMiddleware(wsLogger)
	recovererMiddleware := middlewares2.NewRecovererMiddleware(wsLogger)
	wsportWs := gorillaws.NewWsImpl(gorillaUpgrader, dialer, connectionStore, mux, consumer, wsLogger, loggingMiddleware, recovererMiddleware)
	exampleWsHandler := ws.NewExampleWsHandler()
	wsGroup := groups.NewWsGroup(wsportWs, exampleWsHandler)
	app := http.NewApp(httpServer, envEnv, jwtAuthMiddleware, responseMiddleware, entityGroup, wsGroup, wsportWs)
	return app
}

func InitAsyncApp() *asynctask.App {
	config := async.NewAsynqConfig()
	envEnv := env.NewEnv()
	redisClientOpt := async.NewAsynqRedisClientOpt0(envEnv)
	server := async.NewAsynqServer(config, redisClientOpt)
	serveMux := async.NewAsynqServeMux()
	asyncServer := async.NewAsynqServerImpl(server, serveMux)
	processEntityHandler := handlers2.NewProcessEntityHandler()
	app := asynctask.NewAsyncApp(asyncServer, processEntityHandler)
	return app
}
